# Generated by Django 2.2.9 on 2020-08-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200727_1113'),
        ('posts', '0008_auto_20200726_1505'),
    ]

    operations = [
    ]
